name: Generate yaml manifest with Jinja

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment: development, testing. Default: development'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - testing
      release:
        description: 'Release version'
        required: true
        default: '0.1'
        

jobs:
  upload:
    name: Jinja2 templating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate yaml manifest
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: templates/deployment.yaml.j2
          output_file: dest/deployment.yaml
          data_file: data/${{ github.event.inputs.environment }}_config.yaml
          data_format: yaml
          variables: |
            release=${{ github.event.inputs.release }}

      - name: Check yaml manifest after generation
        working-directory: dest/
        run: |
         cat deployment.yaml

      - name: Commit and push manifest
        run: >
          git config user.email "Ilia.Eriomenco@endava.com" &&
          git config user.name "IliaEriomencoEndava" &&
          git add . &&
          git commit -m "feat: New yaml manifest creation" &&
          git push origin HEAD:main