# This workflow will trigger service repository creation from template repository

name: Generate file and push to repository  

on:
  workflow_dispatch: 
    inputs:
      template-repo-name:
        description: 'Existing template repository'
        default: 'maven-service-template'
        required: true
      service-repo-name:
        description: 'Repository name for creation'
        default: 'backend-test-service'
        required: true 
      protected-branch:
        description: 'Define branch for protection'
        default: 'main'
        required: true 
      repo-allowed-users: 
        description: 'Allowed github users'
        default: '"github-paytrix"'
        required: true      
      repo-allowed-teams: 
        description: 'Allowed github teams'
        default: '""'
        required: true    
      env-name: 
        description: 'Environment: development, testing, staging, production'
        default: 'development'
        required: true    

jobs:
  setup:
    name: Generate file and push to repository 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.TEST_TEMPLATE_REPO_TOKEN }}
      REPO_OWNER: 'Paytrix-IO'
      TEMPLATE_REPO_NAME: ${{ github.event.inputs.template-repo-name }}
      SERVICE_REPO_NAME: ${{ github.event.inputs.service-repo-name }}
      PROTECTED_BRANCH: ${{ github.event.inputs.protected-branch }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Prepare static/service_main_app.yaml
        working-directory: ./static
        run: |
          cat > service_main_app.yaml <<EOF
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ${{ env.SERVICE_REPO_NAME }}
            namespace: default
            finalizers:
              - resources-finalizer.argocd.argoproj.io
            annotations:
              argocd.argoproj.io/manifest-generate-paths: .;../../base
          spec:
            project: default
            source:
              repoURL: 'https://github.com/Paytrix-IO/argo-ops.git'
              path: kustomize/${{ env.SERVICE_REPO_NAME }}/env/${{ github.event.inputs.env-name }}
              targetRevision: HEAD
            destination:
              server: 'https://kubernetes.default.svc' 
              namespace: paytrix
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
          EOF
      - name: Push generated static/service_main_app.yaml to destination folder
        uses: nkoppel/push-files-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ env.GITHUB_TOKEN }}
        with:
          source-files: 'static/'
          destination-username: 'IliaEriomencoEndava'
          destination-repository: 'test-template-repo'
          destination-directory: 'destination'
          commit-email: 'Ilia.Eriomenco@endava.com'
